import { exec } from "child_process";
import fs from "fs";
// const images = [
//   "https://images.unsplash.com/photo-1449426468159-d96dbf08f19f?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
//   "https://images.unsplash.com/photo-1609630875171-b1321377ee65?q=80&w=1880&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
//   "https://images.unsplash.com/photo-1606907568152-58fcb0a0a4e5?q=80&w=1664&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
//   "https://images.unsplash.com/photo-1502744688674-c619d1586c9e?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
//   "https://images.unsplash.com/photo-1614165936126-2ed18e471b3b?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
//   "https://images.unsplash.com/photo-1531327431456-837da4b1d562?q=80&w=1664&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
// ];

const images = ["112", "113", "114", "115", "116", "117"];

const bikes = [
  {
    name: "Trek Fuel EX",
    price: 2200,
    description:
      "A versatile trail bike that's at home on everything from dirt climbs to technical descents.",
    bikeType: "Mountain",
    ageRange: ["12+", "Adult"],
    brand: "Trek",
    numberOfSpeeds: 1,
    color: "Black",
    wheelSize: "27.5",
    modelNumber: "2019",
    image: images[0],
  },
  {
    name: "Specialized Diverge",
    price: 2000,
    description:
      "A gravel bike that can handle anything from smooth pavement to broken roads.",
    bikeType: "Road",
    ageRange: ["12+", "Adult"],
    brand: "Specialized",
    numberOfSpeeds: 21,
    color: "Grey",
    wheelSize: "700c",
    modelNumber: "2020",
    image: images[1],
  },
  {
    name: "Cannondale Topstone",
    price: 1500,
    description: "A comfortable and efficient road bike for casual rides.",
    bikeType: "Road",
    ageRange: ["12+", "Adult"],
    brand: "Cannondale",
    numberOfSpeeds: 21,
    color: "Blue",
    wheelSize: "700c",
    modelNumber: "2021",
    image: images[2],
  },
  {
    name: "Salsa Gravel",
    price: 2500,
    description:
      "A versatile gravel bike that can handle everything from smooth pavement to rough trails.",
    bikeType: "Gravel",
    ageRange: ["12+", "Adult"],
    brand: "Cannondale",
    numberOfSpeeds: 1,
    color: "Green",
    wheelSize: "700c",
    modelNumber: "2020",
    image: images[5],
  },
  {
    name: "Giant TCR",
    price: 1800,
    description:
      "A road bike that's designed for comfort and efficiency, perfect for long rides.",
    bikeType: "Road",
    ageRange: ["12+", "Adult"],
    brand: "Giant",
    numberOfSpeeds: 21,
    color: "Red",
    wheelSize: "700c",
    modelNumber: "2021",
    image: images[4],
  },
  {
    name: "Pinarello Grevil",
    price: 3000,
    description:
      "A gravel bike that's fast and efficient, perfect for challenging terrain.",
    bikeType: "Gravel",
    ageRange: ["12+", "Adult"],
    brand: "Pinarello",
    numberOfSpeeds: 1,
    color: "Black",
    wheelSize: "700c",
    modelNumber: "2020",
    image: images[5],
  },
  {
    name: "Trek Domane",
    price: 2200,
    description:
      "A road bike that's designed for comfort and efficiency, perfect for long rides.",
    bikeType: "Road",
    ageRange: ["12+", "Adult"],
    brand: "Trek",
    numberOfSpeeds: 21,
    color: "Red",
    wheelSize: "700c",
    modelNumber: "2021",
    image: images[1],
  },
  {
    name: "Cannondale Synapse",
    price: 2800,
    description:
      "A road bike that's fast and efficient, perfect for long rides.",
    bikeType: "Road",
    ageRange: ["12+", "Adult"],
    brand: "Cannondale",
    numberOfSpeeds: 21,
    color: "Blue",
    wheelSize: "700c",
    modelNumber: "2020",
    image: images[4],
  },
  {
    name: "Specialized Tarmac",
    price: 2500,
    description:
      "A road bike that's designed for speed and efficiency, perfect for racing.",
    bikeType: "Road",
    ageRange: ["12+", "Adult"],
    brand: "Specialized",
    numberOfSpeeds: 21,
    color: "Black",
    wheelSize: "700c",
    modelNumber: "2021",
    image: images[3],
  },
  {
    name: "Giant Contend",
    price: 1500,
    description:
      "A road bike that's designed for comfort and efficiency, perfect for long rides.",
    bikeType: "Road",
    ageRange: ["12+", "Adult"],
    brand: "Giant",
    numberOfSpeeds: 21,
    color: "Red",
    wheelSize: "700c",
    modelNumber: "2020",
    image: images[0],
  },
  {
    name: "Cannondale Topstone Carbon",
    price: 3000,
    description:
      "A comfortable and efficient road bike for casual rides, built with carbon fiber.",
    bikeType: "Road",
    ageRange: ["12+", "Adult"],
    brand: "Cannondale",
    numberOfSpeeds: 21,
    color: "Blue",
    wheelSize: "700c",
    modelNumber: "2020",
    image: images[1],
  },
  {
    name: "Trek Emonda",
    price: 3500,
    description:
      "A high-performance road bike designed for racing, built with carbon fiber.",
    bikeType: "Road",
    ageRange: ["Adult"],
    brand: "Trek",
    numberOfSpeeds: 21,
    color: "Black",
    wheelSize: "700c",
    modelNumber: "2021",
    image: images[1],
  },
  {
    name: "Specialized Venge",
    price: 3200,
    description:
      "A high-performance road bike designed for racing, built with carbon fiber.",
    bikeType: "Road",
    ageRange: ["Adult"],
    brand: "Specialized",
    numberOfSpeeds: 22,
    color: "Red",
    wheelSize: "700c",
    modelNumber: "2020",
    image: images[2],
  },

  {
    name: "Giant TCR Advanced",
    price: 4000,
    description:
      "A high-performance road bike designed for racing, built with carbon fiber.",
    bikeType: "Road",
    ageRange: ["Adult"],
    brand: "Giant",
    numberOfSpeeds: 22,
    color: "Red",
    wheelSize: "700c",
    modelNumber: "2020",
    image: images[3],
  },
  {
    name: "Canyon Ultimate CFR",
    price: 2000,
    description:
      "A high-performance road bike designed for racing, built with carbon fiber.",
    bikeType: "Road",
    ageRange: ["Adult"],
    brand: "Canyon",
    numberOfSpeeds: 22,
    color: "Blue",
    wheelSize: "700c",
    modelNumber: "2021",
    image: images[4],
  },
  {
    name: "Trek Madone",
    price: 4500,
    description:
      "A high-performance road bike designed for racing, built with carbon fiber.",
    bikeType: "Road",
    ageRange: ["Adult"],
    brand: "Trek",
    numberOfSpeeds: 22,
    color: "Black",
    wheelSize: "700c",
    modelNumber: "2020",
    image: images[1],
  },
  {
    name: "Specialized S-Works Venge",
    price: 5000,
    description:
      "A high-performance road bike designed for racing, built with carbon fiber.",
    bikeType: "Road",
    ageRange: ["Adult"],
    brand: "Specialized",
    numberOfSpeeds: 22,
    color: "Red",
    wheelSize: "700c",
    modelNumber: "2019",
    image: images[3],
  },
  {
    name: "Pinarello Dogma F8",
    price: 10000,
    description:
      "A high-performance road bike designed for racing, built with carbon fiber.",
    bikeType: "Road",
    ageRange: ["Adult"],
    brand: "Pinarello",
    numberOfSpeeds: 22,
    color: "Black",
    wheelSize: "700c",
    modelNumber: "2020",
    image: images[5],
  },
  {
    name: "Giant Trinity Advanced",
    price: 5000,
    description:
      "A high-performance road bike designed for racing, built with carbon fiber.",
    bikeType: "Road",
    ageRange: ["Adult"],
    brand: "Giant",
    numberOfSpeeds: 22,
    color: "Red",
    wheelSize: "700c",
    modelNumber: "2019",
    image: images[2],
  },
];

export default bikes;
